# NUMPY example

In [3]:
import numpy as np

**Numpy의 특징**
* 넘파이(Numpy)는 수치 데이터를 다루는 파이썬 패키지입니다. 
* Numpy의 핵심이라고 불리는 다차원 행렬 자료구조인 ndarray를 통해 벡터 및 행렬을 사용하는 선형 대수 계산에서 주로 사용됩니다. 
* Numpy는 편의성뿐만 아니라, 속도면에서도 순수 파이썬에 비해 압도적으로 빠르다는 장점이 있습니다.

**Numpy의 주요 모듈**
1. np.array() # 리스트, 튜플, 배열로 부터 ndarray(n-dimension array)를 생성
2. np.asarray() # 기존의 array로 부터 ndarray를 생성
3. np.arange() # range와 비슷
4. np.linspace(start, end, num) # [start, end] 균일한 간격으로 num개 생성
5. np.logspace(start, end, num) # [start, end] log scale 간격으로 num개 생성

### 1) np.array()

* 앞서 Numpy의 핵심은 ndarray라고 언급한 바 있습니다. 
* np.array()는 리스트, 튜플, 배열로 부터 ndarray를 생성합니다. 
** 또한 인덱스가 항상 0으로 시작한다는 특징을 갖고 있습니다.

우선 파이썬 자료구조 중 하나인 리스트를 가지고 1차원 배열을 생성해보도록 하겠습니다.

In [8]:
a = np.array([1, 2, 3, 4, 5]) #리스트를 가지고 1차원 배열 생성
print(type(a))
print(a)
print('a.ndim is:',a.ndim) #차원 출력
print('a.shape is:',a.shape) #크기 출력

<class 'numpy.ndarray'>
[1 2 3 4 5]
a.ndim is: 1
a.shape is: (5,)


타입이 numpy.ndarray라고 나오고 있으며, 배열로 생성되었음을 알 수 있습니다. 
* 이제 2차원 배열을 만들어보도록 하겠습니다. 
* 한가지 주의할 점은 array() 안에 하나의 리스트만 들어가므로 **리스트의 리스트**를 넣어야 합니다.

In [7]:
b = np.array([[10, 20, 30], [ 60, 70, 80]]) 
print(b) #출력
print('b.ndim is:',b.ndim) #차원 출력
print('b.shape is:',b.shape) #크기 출력

[[10 20 30]
 [60 70 80]]
b.ndim is: 2
b.shape is: (2, 3)


### 2) ndarray 초기화
위에서는 리스트를 가지고 ndarray를 생성했지만, ndarray를 만드는 다양한 다른 방법이 존재합니다. 
1. **zeros()**는 해당 배열에 모두 0을 삽입하고, 
2. **ones()**는 모두 1을 삽입합니다. 
3. **full()**은 배열에 사용자가 지정한 값을 넣는데 사용하고, 
4. **eye()**는 대각선으로는 1이고 나머지는 0인 2차원 배열을 생성합니다.

In [18]:
# zeros()
a = np.zeros(2)
print('2행 array is :',a)
a= np.zeros((2,3))
print('2행3열 array is:',a)

2행 array is : [0. 0.]
2행3열 array is: [[0. 0. 0.]
 [0. 0. 0.]]


In [19]:
# ones()
a = np.ones((2,3))
print(a)

[[1. 1. 1.]
 [1. 1. 1.]]


In [21]:
# full()
a = np.full((2,3),7)   # 2x3 w/ 7
print(a)

[[7 7 7]
 [7 7 7]]


In [24]:
# eye()
a = np.eye(3)   # 3x3 대각선으로 1이고 나머지는 0인 이차원 배열
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [25]:
# random
a = np.random.random((2,2))
print(a)

[[0.92781567 0.03280858]
 [0.96588292 0.22125374]]


### 3) np.arange()
np.arange()는 지정해준 범위에 대해서 배열을 생성합니다. np.arange()의 범위 지정 방법은 다음과 같습니다.
```
numpy.arange(start, stop, step, dtype)
a = np.arange(n) # 0, ..., n-1까지 범위의 지정.
a = np.arange(i, j, k) # i부터 j-1까지 k씩 증가하는 배열.
```

In [28]:
a = np.arange(10)   # 0 ~ 9
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [29]:
a = np.arange(1,10,2)   # 1부터  9까지 , +2씩 증가
print(a)

[1 3 5 7 9]


### 4) resape()

In [31]:
#0부터 29 까지의 숫자를 생성하는 arange(n) 함수에 배열을 다차원으로 변형하는 reshape()를 통해 배열을 생성합니다.
a = np.array(np.arange(30)).reshape((5,6))
print(a)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]


### 5) Numpy 슬라이싱
```
ndarray를 통해 만든 다차원 배열은 파이썬의 리스트처럼 슬라이스(Slice) 기능을 지원합니다. 
슬라이스 기능을 사용하면 원소들 중 복수 개에 접근할 수 있습니다.
```

In [32]:
a = np.array([[1, 2, 3], [4, 5, 6]])
print(a)

[[1 2 3]
 [4 5 6]]


In [33]:
b=a[0:2, 0:2]
print(b)

[[1 2]
 [4 5]]


In [36]:
b=a[0, :] # 첫번째 행 출력
print('1번째 행 출력 :',b)

b=a[:, 1] # 두번째 열 출력
print('2번째 열 출력 :', b)

1번째 행 출력 : [1 2 3]
2번째 열 출력 : [2 5]


### 6) Numpy 정수 인덱싱(integer indexing)
정수 인덱싱은 원본 배열로부터 부분 배열을 구합니다.

In [42]:
a = np.array([[1,2], [4,5], [7,8]])
b = a[[2, 1],[1, 0]] 
print(b)
print(a[2,1], a[1,0])

[8 4]
8 4


### 7) Numpy 연산
Numpy를 사용하면 배열간 연산을 손쉽게 수행할 수 있습니다. 
* +, -, *, /의 연산자를 사용할 수 있으며, 
* 또는 add(), substract(), multiply(), divide() 함수를 사용할 수도 있습니다.

In [ ]:
x = np.array([1,2,3])
y = np.array([4,5,6])

In [46]:
b = x + y # 각 요소에 대해서 더함
# b = np.add(x, y)와 동일함
print(b)

[5 7 9]


In [47]:
b = x - y # 각 요소에 대해서 빼기
# b = np.substract(x, y)와 동일함
print(b)

[-3 -3 -3]


In [48]:
b = b * x # 각 요소에 대해서 곱셈
# b = np.multiply(b, x)와 동일함
print(b)

[-3 -6 -9]


In [49]:
b = b / x # 각 요소에 대해서 나눗셈
# b = np.divide(b, x)와 동일함
print(b)

[-3. -3. -3.]


```
위에서 *를 통해 수행한 것은 요소별 곱이었습니다. 
Numpy에서 벡터와 행렬의 곱 또는 행렬곱을 위해서는 dot()을 사용해야 합니다.
```

In [50]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])

c = np.dot(a, b)
print(c)

[[19 22]
 [43 50]]
