In [1]:
#RNN Character RNNLM

In [23]:
import numpy as np
from tensorflow.keras.utils import to_categorical

# Preprocessing
---

In [28]:
text = 'hihello'
x_text = 'hihell'
y_text = 'ihello'

char_vocab = sorted(list(set(text)))
print('\nchar_vocab\n',char_vocab)

char_to_index = dict((c, i) for i, c in enumerate(char_vocab))
print('\nchar_to_index\n',char_to_index)

index_to_char ={}
for key , value in char_to_index.items():
    index_to_char[value] = key
print('\nindex_to_char\n',index_to_char)

X = []
for char in x_text:
    t = char_to_index[char]
    X.append(t)
print('\nXsequence\n',X)

Y = []
for char in y_text:
    t = char_to_index[char]
    Y.append(t)
print('\nYsequence\n',Y)

one_hot_xtext = to_categorical(X)
one_hot_ytext = to_categorical(Y)

print('\none_hot_xtext\n',one_hot_xtext)
print('\none_hot_ytext\n',one_hot_ytext)


char_vocab
 ['e', 'h', 'i', 'l', 'o']

char_to_index
 {'e': 0, 'h': 1, 'i': 2, 'l': 3, 'o': 4}

index_to_char
 {0: 'e', 1: 'h', 2: 'i', 3: 'l', 4: 'o'}

Xsequence
 [1, 2, 1, 0, 3, 3]

Ysequence
 [2, 1, 0, 3, 3, 4]

one_hot_xtext
 [[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 1. 0. 0.]
 [1. 0. 0. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]]

one_hot_ytext
 [[0. 0. 1. 0. 0.]
 [0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [20]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, LSTM
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [36]:
model = Sequential()
model.add(LSTM(5,input_shape=(1,5)))
model.add(Dense(5, activation='softmax'))

In [37]:
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
model.fit(one_hot_xtext, one_hot_ytext,epochs=10, verbose=2)

ValueError: Error when checking input: expected unified_lstm_4_input to have 3 dimensions, but got array with shape (6, 4)