In [58]:
import numpy as np
from keras.utils import np_utils
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import make_column_transformer

pdca =np.array(['plan', 'do', 'sea', 'action'])

# Integer encode
label_encoder = LabelEncoder()
int_pdca = label_encoder.fit_transform(pdca)
print('int_pdca', int_pdca, '\n', sep='\n')

# binary encode
onehot_encoder = OneHotEncoder(sparse=False)
int_pdca = int_pdca.reshape(len(int_pdca),1)
#onehot_pdca = onehot_encoder.fit_transform(int_pdca)                            
#print('onehot_pdca', onehot_pdca, '\n',sep='\n')               

################

onehot_pdca = np_utils.to_categorical(int_pdca)
print('onehot_pdca', onehot_pdca, '\n',sep='\n')     


int_pdca
[2 1 3 0]


onehot_pdca
[[0. 0. 1. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 1.]
 [1. 0. 0. 0.]]


